### ISSUE TITLE
Install git inside the container

### ISSUE THREAD

**Issue by leosuncin** [beevelop/docker-android-nodejs#170]
First thanks for your work.
Could you also install git? some NPM packages need it for install and Yarn can install repositories using git.
<details>
<pre>
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
</pre>
</details>

**Comment by beevelop** [comment]
Why not? Sounds like a good idea.

**Comment by beevelop** [comment]
Should be available in `:latest` and `:next` as well as all subsequent releases.
