### ISSUE TITLE
Upgrade node to latest LTS

### ISSUE THREAD

**Issue by beruic** [beevelop/docker-android-nodejs#337]
Newest LTS of NodeJS is 12.16.1. Please upgrade.

**Comment by beevelop** [comment]
Android Q with Node.js 12 is now in the master!

**Comment by beruic** [comment]
Should you perhaps push an updated tag to docker hub so dependent projects don't have to rely on `:latest` since it will always be a moving target?

**Comment by beevelop** [comment]
Tagged it as `v12.16.1`. Should trigger the builds on Docker Hub too.
