### ISSUE TITLE
Newest build does not contain Java

### ISSUE THREAD

**Issue by beruic** [beevelop/docker-android-nodejs#339]
I checked out the repo and did a build in Docker.

Among other things, `openjdk-8-jdk` is removed during one of the auto removes.
I guess this might need to be fixed upstream such that the package is marked manual to prevent it from being removed.

The following tags need to be rebuilt:
- `beevelop/android-nodejs:latest`
- `beevelop/android-nodejs:v12.16.1`

`beevelop/android-nodejs:12` seems unaffected, but I guess it should (as per normal conventions) be updated to be the same as `beevelop/android-nodejs:v12.16.1`.

**Comment by beruic** [comment]
Looking a bit further into it, I have discovered that it is the following line that marks waaaay too many packages as automatically installed, and thus removable by `autoremove` (you should consider using `apt` instead of `apt-get` BTW).

**Comment by SantiagoValdez** [comment]
I have the same problem.

**Comment by stereonom** [comment]
Same same 😢

**Comment by alex-outsourci** [comment]
Same here

**Comment by beruic** [comment]
Full disclosure: We moved to CapacitorJS, so I have no further interest in this issue. I recommend you do the same.
