### ISSUE TITLE
Release to doocker latest version

### ISSUE THREAD

**Issue by alesrosina** [beevelop/docker-android-nodejs#343]
Since you've already updated this image to Android 11, would be also nice to upload it to docker hub. There is still Android 10 version and since Play Store now requires SDK version 30, that would be very nice.

Thank you!

**Comment by zommerfelds** [comment]
Same for Android 12

[v2022.06.1](https://github.com/beevelop/docker-android/releases/tag/v2022.06.1)

A new release would be appreciated! :)

**Comment by jbchr** [comment]
Would appreciate this too :)

**Comment by beevelop** [comment]
Release `v2023.01.1` is available with all components updated (Java 11, Android 33, Node 16). Hope that helps.
